### ISSUE TITLE
MacOS needs updating `rsync` to work

### ISSUE THREAD

**Issue by TriplEight** [sgeisler/cargo-remote#10]
The thing what really helped `cargo-remote` to work on macos is 
```
brew install rsync
```
The patch #3 didn't help at all. Neither before nor after `brew install rsync`.
Please follow @kianenigma advice there.

**Comment by sgeisler** [comment]
Ok, but did #3 break anything? I'm not a Mac user, so I can't test this. But I'll add a remark to the README. Do Mac devs know what `brew` is or should I link to somewhere?

**Comment by kianenigma** [comment]
> Do Mac devs know what brew is or should I link to somewhere?

a Dev should know what it is I suppose. 

> Ok, but did #3 break anything? I'm not a Mac user, so I can't test this. 

I just compiled and linked the latest master and it still works fine for me, given the updated rsync. Though I don't get colored output so I will revert.

**Comment by sgeisler** [comment]
So #3 broke the coloring and it worked before? Then I don't understand @TriplEight's comment in #3 tbh.

**Comment by kianenigma** [comment]
Yeah don't know why. Maybe it is the wasm runner that does not show them? 
<img width="1665" alt="Screenshot 2019-11-21 at 10 55 01" src="https://user-images.githubusercontent.com/5588131/69327188-61243780-0c4d-11ea-9d25-61cd7127d6b4.png">

**Comment by kianenigma** [comment]
also the progress bar is gone for some reason

**Comment by sgeisler** [comment]
Did you test with the pre-#3 version too?

**Comment by TriplEight** [comment]
> So #3 broke the coloring and it worked before? Then I don't understand @TriplEight's comment in #3 tbh. If that's the case I'll revert #3 too.

I also don't have a Mac to test on, was asking colleagues to do that xD
