### ISSUE TITLE
[FR] transparent use through rustup toolchain

### ISSUE THREAD

**Issue by ildar** [sgeisler/cargo-remote#18]
would be very nice having `cargo` (and maybe `rls` and `rustc`, later) used with usual syntax but remotely. That need providing proxy executables.
`rustup` already does similar thing: proxy-ing different toolchains.
cargo-remote could ideally just add another toolcahain representing the remote one.
Also that would provide all IDEs with the remote power at no cost.

**Comment by sgeisler** [comment]
That's a very interesting idea, but I fear also very out of scope here. There are a lot of assumptions of IDEs you'll inadvertently break (e.g. being able to attack a debugger when running some binary or there even being a local binary). I'd love to see this executed well, but will not put any energy into it.

**Comment by ildar** [comment]
You're right. We can leave aside IDE questions here.
The rest seems quite obvious, like one-liners in shell executing original
cargo-remote.

Note: I'll do some experimenting but I'm an hour-old rustacean so can
easily get something wrong.

**Comment by ildar** [comment]
JFYI: ended up writing a separate tool:
https://github.com/ildar/rustup-toolchain-remote

**Comment by sgeisler** [comment]
Awesome!
