### ISSUE TITLE
Compile errors under Windows 10

### ISSUE THREAD

**Issue by rts-gordon** [sgeisler/cargo-remote#20]
Hi @sgeisler ,

   I have download cargo-remote source code and compiled it, there is an error:
```
error[E0433]: failed to resolve: could not find `BaseDirectories` in `xdg`
  --> src\config.rs:69:41
   |
69 |         if let Some(config_file) = xdg::BaseDirectories::with_prefix("cargo-remote")
   |                                         ^^^^^^^^^^^^^^^ could not find `BaseDirectories` in `xdg`
```

Would you like to take a look at this, thanks a lot.

OS: Windows 10
Cargo:  1.52.0

**Comment by Captain-Of-Coit** [comment]
XDG is only available on Linux, so replacing the usage with something like https://docs.rs/home/latest/home/fn.home_dir.html is required for Windows compat.
