### ISSUE TITLE
How to set remote environment variables?

### ISSUE THREAD

**Issue by theronic** [sgeisler/cargo-remote#5]
E.g. I need to set PKG_CONFIG_ALLOW_CROSS=1 on remote host to specify --target=...

**Comment by General-Beck** [comment]
Two [options](https://github.com/sgeisler/cargo-remote#flags-and-options) are now supported for managing a remote environment.

**Comment by sgeisler** [comment]
Thanks for pointing that out, this issue was closed by #8 .
